#!/bin/bash
APT_OPTIONS="-q -y"
ETH1_IP="192.168.0.1"
ETH1_NETMASK="255.255.255.0"
ETH1_BROADCAST="192.168.0.255"

# Should be no need to edit past this point
ETH1_MAC=`ifconfig eth1 | grep HWaddr | awk '{print $NF}'`
HOSTNAME=`hostname`
FQDN=`hostname --fqdn`

function configure_eth1()
{
    grep -q '^iface eth1' /etc/network/interfaces || \
	cat >> /etc/network/interfaces <<EOF
auto eth1
iface eth1 inet static
  address ${ETH1_IP}
  netmask ${ETH1_NETMASK}
  broadcast ${ETH1_BROADCAST}
EOF

    ifup eth1
}

function install_shorewall()
{
    apt-get ${APT_OPTIONS} install shorewall
}

function configure_shorewall()
{
    if [ ! -f /etc/shorewall/interfaces ]; then
    # Configure shorewall for basic masquerading of eth1 internal
    # network to eth0 external network
	cp /etc/shorewall/shorewall.conf /etc/shorewall/shorewall.conf.orig
	cp /usr/share/doc/shorewall/examples/two-interfaces/* /etc/shorewall
	gunzip -f /etc/shorewall/shorewall.conf.gz

	# Make sure dhcp is enabled on local zone
	grep -q '^loc.*dhcp.*' /etc/shorewall/interfaces || \
	    perl -pi.bak -E "s/loc (.*)/loc \$1,dhcp/g" /etc/shorewall/interfaces
	# Local shorewall rules separated out from default settings
	mkdir -p /etc/shorewall/conf.d
	echo 'SHELL for f in /etc/shorewall/conf.d/*.conf; do echo "INCLUDE $f"; done' >> /etc/shorewall/rules
	echo '# Sample rule file for shorewall' > /etc/shorewall/conf.d/example-${FQDN}.conf

	# Shorewall starts by defualt
	perl -pi.bak -E "s/^startup=0/startup=1/g" /etc/default/shorewall
	perl -pi.bak -E "s/^STARTUP_ENABLED=No/STARTUP_ENABLED=Yes/g" /etc/shorewall/shorewall.conf
	
    else
	echo
	echo Not configuring shorewall -- /etc/shorewall/interfaces exists.
	echo Remove it if you want to overwrite local changes.
	echo
    fi
}

function install_dhcpd()
{
    apt-get ${APT_OPTIONS} install isc-dhcp-server
}

function install_dns() {
    apt-get install maradns
}

function configure_dns()
{
    # Allow DNS traffic from local zone
    echo 'DNS(ACCEPT) loc $FW' > /etc/shorewall/conf.d/dns-${FQDN}.conf
}

function restart_shorewall()
{
    /etc/init.d/shorewall restart
}

BASEDIR=`dirname $0`

cd ${BASEDIR}
FUNCTION_LIST="
        configure_shorewall
	restart_shorewall
"

for name in ${FUNCTION_LIST}; do
    echo === Running ${name}\(\) ===
    ${name}
    echo
done
