#!/bin/bash
TFTPDIR=/srv/tftp
MIRROR=http://ftp.debian.org/debian
DISTRO=wheezy
cd ${TFTPDIR}
mkdir -p pxelinux.cfg
for ARCH in amd64 i386; do
    NETBOOTURL=${MIRROR}/dists/${DISTRO}/main/installer-${ARCH}/current/images/netboot
    (mkdir -p netboot-sources/${ARCH} && \
	cd netboot-sources/${ARCH} && \
	wget -nd -m ${NETBOOTURL}/netboot.tar.gz && \
	cd ../.. && \
	tar -zxf netboot-sources/${ARCH}/netboot.tar.gz \
	    ./debian-installer/${ARCH} && \
	cd pxelinux.cfg && \
	ln -sf ../debian-installer/${ARCH}/pxelinux.cfg/default \
	    debian-installer-${ARCH} && \
	cd ..
	)
done

# ${ARCH} is set to last value from for loop. This is ok, since all
# pxelinux.0 files should be identical.

ln -sf debian-installer/${ARCH}/pxelinux.0 .

ln -sf debian-installer d-i

# Create preseed files and menu entries as needed. Preseed folder also
# needs a basic puppet.conf, normally provided in firewall-bootstrap.
if [ -f /var/www/preseed.txt ]; then
    for ARCH in amd64 i386; do
        cat >> ${TFTPDIR}/debian-installer/${ARCH}/boot-screens/txt.cfg <<EOD
label preseed
menu label ^Preseeded install
menu default
kernel debian-installer/${ARCH}/linux
append auto locale=en_US keymap=us url=http://`hostname --fqdn`/preseed.txt priority=critical vga=788 initrd=debian-installer/${ARCH}/initrd.gz -- quiet
EOD
    done
fi

# Let puppet modify the necessary syslinux menu files as needed
# (not used in firewall-bootstrap)
# puppet agent -t
